### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [team-mount-ventoux/JayPS-AndroidApp#31]
Would you mind attaching the `.apk` file to the `releases/` here at Github?

**Comment by IzzySoft** [comment]
Just asking: is there a chance, or did you already abandon the project? :scream_cat:

**Comment by IzzySoft** [comment]
Hm, seems to be the latter then :cry:

**Comment by jay3** [comment]
We had a trademark issue, but the app is now back on Google Play with a new name: JayPS

**Comment by IzzySoft** [comment]
Glad to read you're back (and the issue solved)! So will you start attaching the `.apk` to the corresponding `releases/` then?

**Comment by jay3** [comment]
Sure https://github.com/team-mount-ventoux/JayPS-AndroidApp/releases/tag/v3.0.0

**Comment by IzzySoft** [comment]
Cool, thanks! Find it [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.njackson) now as well (should be automatically updated within 24h of your publishing a new tag with an `.apk` attached here).

Note: You might want to skip the leading "v" in the `versionName` (but not in the tag name).

**Comment by IzzySoft** [comment]
@jay3 just wondering: was that the last release, or are you still maintaining the app? No commit since then.
